from SonarPythonAnalyzerFakeStub import CustomStubBase

class OpenInterpreter(CustomStubBase):
    def __init__(
            self,
            messages=...,
            offline=...,
            auto_run=...,
            verbose=...,
            debug=...,
            max_output=...,
            safe_mode=...,
            shrink_images=...,
            loop=...,
            loop_message=...,
            loop_breakers=...,
            disable_telemetry=...,
            in_terminal_interface=...,
            conversation_history=...,
            conversation_filename=...,
            conversation_history_path=...,
            os=...,
            speak_messages=...,
            llm=...,
            system_message=...,
            custom_instructions=...,
            user_message_template=...,
            always_apply_user_message_template=...,
            code_output_template=...,
            empty_code_output_template=...,
            code_output_sender=...,
            computer=...,
            sync_computer=...,
            import_computer_api=...,
            skills_path=...,
            import_skills=...,
            multi_line=...,
            contribute_conversation=...,
            plain_text_display=...,
    ) -> OpenInterpreter: ...
