from typing import Any

class FieldInfo: ...

class PrivateAttr:
    def __init__(self, default: Any = ..., **kwargs: Any) -> None: ...

def Field(default: Any = ..., **kwargs: Any) -> FieldInfo: ...
