# URL types (FQN: pydantic.networks.*)
# All URL classes share the same interface — they wrap pydantic_core.Url internally.
class AnyUrl:
    scheme: str
    host: str
    path: str
    port: int
    query: str | None
    fragment: str | None
    username: str | None
    password: str | None
    def unicode_string(self) -> str: ...
    def unicode_host(self) -> str: ...
    def query_params(self) -> list: ...
    def encoded_string(self) -> str: ...

class AnyHttpUrl(AnyUrl): ...
class HttpUrl(AnyUrl): ...
class FileUrl(AnyUrl): ...
class AnyWebsocketUrl(AnyUrl): ...
class WebsocketUrl(AnyUrl): ...
class FtpUrl(AnyUrl): ...
class AmqpDsn(AnyUrl): ...
class CockroachDsn(AnyUrl): ...
class KafkaDsn(AnyUrl): ...
class RedisDsn(AnyUrl): ...
class PostgresDsn(AnyUrl): ...
class MongoDsn(AnyUrl): ...

# pydantic.networks.Url — identical to pydantic_core.Url at runtime (same object in pydantic v2).
# Defined here as a class so `from pydantic.networks import Url` resolves to FQN pydantic.networks.Url
# (cross-stub re-exports are not followed by the type engine).
# TODO: consolidate to pydantic_core.Url on the security side (FastApiSource.java).
class Url:
    scheme: str
    host: str
    path: str
    port: int
    query: str | None
    fragment: str | None
    username: str | None
    password: str | None
    def unicode_string(self) -> str: ...
    def unicode_host(self) -> str: ...
    def query_params(self) -> list: ...

# Network address types (FQN: pydantic.networks.*)
class IPvAnyAddress: ...
class IPvAnyInterface: ...
class IPvAnyNetwork: ...

# Email / name types (FQN: pydantic.networks.*)
class EmailStr(str): ...
class NameEmail: ...
