from typing import Any
from decimal import Decimal
from datetime import date, datetime
from pathlib import Path
from uuid import UUID

# Real classes defined in pydantic.types (FQN: pydantic.types.*)
class SecretStr:
    def __init__(self, secret_value: str) -> None: ...
    def get_secret_value(self) -> str: ...

class ByteSize(int): ...
class Json: ...
class ImportString: ...
class StringConstraints: ...
class PaymentCardNumber: ...
class PastDate(date): ...
class FutureDate(date): ...
class PastDatetime(datetime): ...
class FutureDatetime(datetime): ...
class AwareDatetime(datetime): ...
class NaiveDatetime(datetime): ...

# Constrained type factories (FQN: pydantic.types.*)
class conint(int):
    def __init__(self, *, strict: bool = ..., gt: int = ..., ge: int = ..., lt: int = ..., le: int = ..., multiple_of: int = ...) -> None: ...

class conlist(list):
    def __init__(self, item_type: Any = ..., *, min_length: int = ..., max_length: int = ...) -> None: ...

class conset(set):
    def __init__(self, item_type: Any = ..., *, min_length: int = ..., max_length: int = ...) -> None: ...

class confrozenset(frozenset):
    def __init__(self, item_type: Any = ..., *, min_length: int = ..., max_length: int = ...) -> None: ...

class conbytes(bytes):
    def __init__(self, *, strict: bool = ..., min_length: int = ..., max_length: int = ...) -> None: ...

class constr(str):
    def __init__(self, *, strip_whitespace: bool = ..., to_upper: bool = ..., to_lower: bool = ..., strict: bool = ..., min_length: int = ..., max_length: int = ..., pattern: str = ..., ascii_only: bool = ...) -> None: ...

class confloat(float):
    def __init__(self, *, strict: bool = ..., gt: float = ..., ge: float = ..., lt: float = ..., le: float = ..., multiple_of: float = ..., allow_inf_nan: bool = ...) -> None: ...

class condecimal(Decimal):
    def __init__(self, *, strict: bool = ..., gt: Any = ..., ge: Any = ..., lt: Any = ..., le: Any = ..., multiple_of: Any = ..., max_digits: int = ..., decimal_places: int = ..., allow_inf_nan: bool = ...) -> None: ...

class condate(date):
    def __init__(self, *, strict: bool = ..., gt: date = ..., ge: date = ..., lt: date = ..., le: date = ...) -> None: ...

# Annotated aliases — no real class, defined in pydantic.types as Annotated[<base>, ...]
# Best FQN is pydantic.types.* (where they are defined in pydantic source)
class StrictStr(str): ...

class PositiveInt(int): ...
class NegativeInt(int): ...
class NonNegativeInt(int): ...
class NonPositiveInt(int): ...

class PositiveFloat(float): ...
class NegativeFloat(float): ...
class NonNegativeFloat(float): ...
class NonPositiveFloat(float): ...
class FiniteFloat(float): ...

class FilePath(Path): ...
class DirectoryPath(Path): ...
class NewPath(Path): ...

class Base64Bytes(bytes): ...
class Base64UrlBytes(bytes): ...
class Base64Str(str): ...
class Base64UrlStr(str): ...

class UUID1(UUID): ...
class UUID3(UUID): ...
class UUID4(UUID): ...
class UUID5(UUID): ...
