from typing import Any
from .module import Module

class Transformer(Module):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, *args, **kwargs) -> Any: ...

class TransformerEncoder(Module):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, *args, **kwargs) -> Any: ...

class TransformerDecoder(Module):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, *args, **kwargs) -> Any: ...

class TransformerEncoderLayer(Module):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, *args, **kwargs) -> Any: ...

class TransformerDecoderLayer(Module):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, *args, **kwargs) -> Any: ...