env:
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash
  DEPLOY_PULL_REQUEST: false
  IS_COMMUNITY: true

build_container_definition: &BUILD_CONTAINER_DEFINITION
  eks_container:
    dockerfile: .cirrus/python-env.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    builder_role: cirrus-builder
    builder_image: docker-builder-v*
    builder_instance_type: t3.small
    region: eu-central-1
    namespace: default
    cpu: 2
    memory: 4G

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $LOCAL == "1" || ($CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BUILD_SOURCE == 'api'  || $CIRRUS_BRANCH =~ "dogfood-on-.*"))

build_task:
  <<: *BUILD_CONTAINER_DEFINITION
  eks_container:
    cpu: 4

  <<: *ONLY_SONARSOURCE_QA
  env:
    # analysis on next
    SONAR_TOKEN: dummy-value
    SONAR_HOST_URL: dummy-value
    CIRRUS_CLONE_DEPTH: 50
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  build_script:
    - rm -rf private
    - source cirrus-env BUILD
    - regular_mvn_build_deploy_analyze -DskipTests=true -Dsonar.skip=true -P-typeshed_serializer,-sign,-private
    - ./check-license-compliance.sh
  cleanup_before_cache_script: cleanup_maven_repository

test_analyze_task:
  depends_on:
    - build
  <<: *BUILD_CONTAINER_DEFINITION
  eks_container:
    cpu: 4
    memory: 4G
  <<: *ONLY_SONARSOURCE_QA
  env:
    # analysis on next
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    CIRRUS_CLONE_DEPTH: 50
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  submodules_script:
    - git submodule update --init --jobs 4
    - cd python-frontend/typeshed_serializer/resources/python-type-stubs
    - git sparse-checkout set stubs/sklearn
    - git checkout
  analyze_script:
    - rm -rf private
    - source cirrus-env BUILD
    - PULL_REQUEST_SHA=$GIT_SHA1 ./.cirrus/test_analyze.sh -Dsonar.skip=true
  cleanup_before_cache_script: cleanup_maven_repository
