from collections.abc import Iterator
from django.db.models.base import Model

class AppConfig:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_model(self, model_name: str, require_ready: bool = ...) -> type[Model]: ...
    def get_models(
        self, include_auto_created: bool = ..., include_swapped: bool = ...
    ) -> Iterator[type[Model]]: ...
