from django.db.models.base import Model


class Apps:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_models(
        self, include_auto_created: bool = ..., include_swapped: bool = ...
    ) -> list[type[Model]]: ...
    def get_model(
        self, app_label: str, model_name: str | None = ..., require_ready: bool = ...
    ) -> type[Model]: ...

apps: Apps
