name: 'Config Sonar Python'
description: 'Configure maven and update versions for sonar-python project'

outputs:
  current-version:
    description: 'Current version of the project'
    value: ${{ steps.config-maven.outputs.current-version }}

runs:
  using: 'composite'
  steps:
    - name: Configure public Maven project
      id: config-maven
      uses: SonarSource/ci-github-actions/config-maven@v1

    - name: Configure Private Maven project
      uses: SonarSource/ci-github-actions/config-maven@v1
      with:
        working-directory: private
      env:
        CONFIG_MAVEN_COMPLETED: ''
        #SKIP: 'false'
        CURRENT_VERSION: ''
        PROJECT_VERSION: ''
