from xml.etree.ElementTree import ElementTree
from xml.etree.ElementTree import Element

from typing import Any, List, Iterator

class _ElementTree(CustomStubBase):
    def findall(self, *args, **kwargs) -> List: ...
    def find(self, *args, **kwargs) -> _Element: ...
    def findtext(self, *args, **kwargs) -> str: ...
    def getroot(self, *args, **kwargs) -> _Element: ...
    def parse(self, *args, **kwargs) -> _Element: ...
    def iterfind(self, *args, **kwargs) -> Iterator: ...
    def xpath(self, *args, **kwargs) -> Any: ...

class _Element(CustomStubBase):
    def findall(self, *args, **kwargs) -> List: ...
    def find(self, *args, **kwargs) -> _Element: ...
    def findtext(self, *args, **kwargs) -> str: ...
    def iterfind(self, *args, **kwargs) -> Iterator: ...
    def xpath(self, *args, **kwargs) -> Any: ...
    def __getitem__(self, *args, **kwargs) -> _Element: ...

def parse(*args, **kwargs) -> _ElementTree: ...
def fromstring(*args, **kwargs) -> _ElementTree: ...
