from SonarPythonAnalyzerFakeStub import CustomStubBase

class AssertionBuilder(CustomStubBase):
    def described_as(self, description: str) -> "AssertionBuilder": ...
    def snapshot(self, name: str) -> "AssertionBuilder": ...
    def is_equal_to(self, other: object = ...) -> "AssertionBuilder": ...
    def is_not_equal_to(self, other: object) -> "AssertionBuilder": ...

def assert_that(val: object = ...) -> AssertionBuilder: ...
