class SMTP:
    def sendmail(self, from_addr: Any, to_addrs: Any, msg: Any, mail_options: Optional[Any], rcpt_options: Optional[Any]) -> None: ...
    def send_message(self, msg: Any, from_addr: Optional[Any], to_addrs: Optional[Any], mail_options: Optional[Any], rcpt_options: Optional[Any]) -> None: ...
    def starttls(self, keyfile: Optional[Any], certfile: Optional[Any], context: Optional[Any]) -> None: ...

class SMTP_SSL(SMTP): ...
