from SonarPythonAnalyzerFakeStub import CustomStubBase
from langchain_experimental.utilities.python import PythonREPL
from typing import Dict, Type, Optional


class PythonREPLTool(CustomStubBase):
    name: str = ...
    description: str = ...
    python_repl: PythonREPL = ...
    sanitize_input: bool = ...


class PythonAstREPLTool(CustomStubBase):
    name: str = ...
    description: str = ...
    globals: Optional[Dict] = ...
    locals: Optional[Dict] = ...
    sanitize_input: bool = ...
    args_schema: Type[BaseModel] = ...
