import json as _json
import typing as t
from ..app import Flask
from ..wrappers import Response

class JSONEncoder(_json.JSONEncoder):
    def __init__(self, **kwargs) -> None: ...
    def default(self, o: t.Any) -> t.Any: ...

class JSONDecoder(_json.JSONDecoder):
    def __init__(self, **kwargs) -> None: ...

def dumps(obj: t.Any, *, app: Union[Flask, None] = ..., **kwargs: t.Any) -> str: ...
def dump(obj: t.Any, fp: t.IO[str], *, app: Union[Flask, None] = ..., **kwargs: t.Any) -> None: ...
def loads(s: Union[str, bytes], *, app: Union[Flask, None] = ..., **kwargs: t.Any) -> t.Any: ...
def load(fp: t.IO[t.AnyStr], *, app: Union[Flask, None] = ..., **kwargs: t.Any) -> t.Any: ...
def htmlsafe_dumps(obj: t.Any, **kwargs: t.Any) -> str: ...
def htmlsafe_dump(obj: t.Any, fp: t.IO[str], **kwargs: t.Any) -> None: ...
def jsonify(*args: t.Any, **kwargs: t.Any) -> Response: ...
