from typing import Dict, Any

class HttpRequest(CustomStubBase):
    GET: QueryDict = ...
    POST: QueryDict = ...
    COOKIES: QueryDict = ...
    META: QueryDict = ...
    FILES: QueryDict = ...
    headers: QueryDict = ...

class QueryDict(CustomStubBase):
    def get(self, *args, **kwargs) -> str: ...
    def __getitem__(self, *args, **kwargs) -> str: ...
