
dockerfile_parse.constants*²
__annotations__*dockerfile_parse.constants.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict*38*39*310*311*312*313*
DOCKERFILE_FILENAME.dockerfile_parse.constants.DOCKERFILE_FILENAME
builtins.str"builtins.str*38*39*310*311*312*313*
COMMENT_INSTRUCTION.dockerfile_parse.constants.COMMENT_INSTRUCTION
builtins.str"builtins.str*38*39*310*311*312*313