
dockerfile_parse.parser¢
	KeyValues!dockerfile_parse.parser.KeyValues"builtins.dict*ö
__init__*dockerfile_parse.parser.KeyValues.__init__"
None*P
selfF
!dockerfile_parse.parser.KeyValues"!dockerfile_parse.parser.KeyValues*á

key_valuesw
)typing.Mapping[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"typing.Mapping*`
parserT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParserz38z39z310z311z312z313*Ã
__delitem__-dockerfile_parse.parser.KeyValues.__delitem__"
None*HF
!dockerfile_parse.parser.KeyValues"!dockerfile_parse.parser.KeyValues*
builtins.str"builtins.strz38z39z310z311z312z313*Ï
__setitem__-dockerfile_parse.parser.KeyValues.__setitem__"
None*HF
!dockerfile_parse.parser.KeyValues"!dockerfile_parse.parser.KeyValues*
builtins.str"builtins.str*
builtins.str"builtins.strz38z39z310z311z312z313*ﬁ
__eq__(dockerfile_parse.parser.KeyValues.__eq__"
builtins.bool"builtins.bool*HF
!dockerfile_parse.parser.KeyValues"!dockerfile_parse.parser.KeyValues*$"
builtins.object"builtins.objectz38z39z310z311z312z313*¬
__hash__*dockerfile_parse.parser.KeyValues.__hash__"
builtins.int"builtins.int*P
selfF
!dockerfile_parse.parser.KeyValues"!dockerfile_parse.parser.KeyValuesz38z39z310z311z312z313j38j39j310j311j312j313rû
parser_attr-dockerfile_parse.parser.KeyValues.parser_attrD
Union[builtins.str,None]
builtins.str"builtins.str
None*38*39*310*311*312*313r§
parser(dockerfile_parse.parser.KeyValues.parserT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser*38*39*310*311*312*313g
Labelsdockerfile_parse.parser.Labels"!dockerfile_parse.parser.KeyValuesj38j39j310j311j312j313c
Envsdockerfile_parse.parser.Envs"!dockerfile_parse.parser.KeyValuesj38j39j310j311j312j313c
Argsdockerfile_parse.parser.Args"!dockerfile_parse.parser.KeyValuesj38j39j310j311j312j313k
_InstructionDict(dockerfile_parse.parser._InstructionDict"typing._TypedDictj38j39j310j311j312j313œ-
DockerfileParser(dockerfile_parse.parser.DockerfileParser"builtins.object*¢
__init__1dockerfile_parse.parser.DockerfileParser.__init__"
None*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser*P
pathD
Union[builtins.str,None]
builtins.str"builtins.str
None *3
cache_content
builtins.bool"builtins.bool *1
env_replace
builtins.bool"builtins.bool *Ã

parent_envπ
4Union[builtins.dict[builtins.str,builtins.str],None]u
(builtins.dict[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"builtins.dict
None *Ñ
fileobju
#Union[typing.IO[builtins.str],None]B
typing.IO[builtins.str]
builtins.str"builtins.str"	typing.IO
None *Ã

build_argsπ
4Union[builtins.dict[builtins.str,builtins.str],None]u
(builtins.dict[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"builtins.dict
None z38z39z310z311z312z313*”
	structure2dockerfile_parse.parser.DockerfileParser.structure"á
#builtins.list[TypeAlias[TypedDict]]Q
TypeAlias[TypedDict]
	TypedDict"(dockerfile_parse.parser._InstructionDict"builtins.list*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser0:property`z38z39z310z311z312z313*›
json-dockerfile_parse.parser.DockerfileParser.json"
builtins.str"builtins.str*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser0:property`z38z39z310z311z312z313*Ò
is_multistage6dockerfile_parse.parser.DockerfileParser.is_multistage"
builtins.bool"builtins.bool*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser0:property`z38z39z310z311z312z313*ˇ
	add_lines2dockerfile_parse.parser.DockerfileParser.add_lines"
None*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser*'
lines
builtins.str"builtins.str*Y

all_stagesG
Union[builtins.bool,None]
builtins.bool"builtins.bool
None *W
at_startG
Union[builtins.bool,None]
builtins.bool"builtins.bool
None *[
skip_scratchG
Union[builtins.bool,None]
builtins.bool"builtins.bool
None z38z39z310z311z312z313*≤
add_lines_at5dockerfile_parse.parser.DockerfileParser.add_lines_at"
None*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser*ç
anchorÄ
IUnion[builtins.str,builtins.int,builtins.dict[builtins.str,builtins.int]]
builtins.str"builtins.str
builtins.int"builtins.intu
(builtins.dict[builtins.str,builtins.int]
builtins.str"builtins.str
builtins.int"builtins.int"builtins.dict*'
lines
builtins.str"builtins.str*V
replaceG
Union[builtins.bool,None]
builtins.bool"builtins.bool
None *T
afterG
Union[builtins.bool,None]
builtins.bool"builtins.bool
None z38z39z310z311z312z313*ÿ
context_structure:dockerfile_parse.parser.DockerfileParser.context_structure"}
,builtins.list[dockerfile_parse.util.Context]>
dockerfile_parse.util.Context"dockerfile_parse.util.Context"builtins.list*^
selfT
(dockerfile_parse.parser.DockerfileParser"(dockerfile_parse.parser.DockerfileParser0:property`z38z39z310z311z312z313j38j39j310j311j312j313rõ
fileobj0dockerfile_parse.parser.DockerfileParser.fileobjB
typing.IO[builtins.str]
builtins.str"builtins.str"	typing.IO*38*39*310*311*312*313rÖ
dockerfile_path8dockerfile_parse.parser.DockerfileParser.dockerfile_path
builtins.str"builtins.str*38*39*310*311*312*313rÉ
cache_content6dockerfile_parse.parser.DockerfileParser.cache_content
builtins.bool"builtins.bool*38*39*310*311*312*313rÉ
cached_content7dockerfile_parse.parser.DockerfileParser.cached_content
builtins.str"builtins.str*38*39*310*311*312*313r
env_replace4dockerfile_parse.parser.DockerfileParser.env_replace
builtins.bool"builtins.bool*38*39*310*311*312*313r‘

parent_env3dockerfile_parse.parser.DockerfileParser.parent_envu
(builtins.dict[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"builtins.dict*38*39*310*311*312*313r‘

build_args3dockerfile_parse.parser.DockerfileParser.build_argsu
(builtins.dict[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"builtins.dict*38*39*310*311*312*313rü
lines.dockerfile_parse.parser.DockerfileParser.linesJ
builtins.list[builtins.str]
builtins.str"builtins.str"builtins.list*38*39*310*311*312*313ru
content0dockerfile_parse.parser.DockerfileParser.content
builtins.str"builtins.str*38*39*310*311*312*313r≥
parent_images6dockerfile_parse.parser.DockerfileParser.parent_imagesN
typing.Sequence[builtins.str]
builtins.str"builtins.str"typing.Sequence*38*39*310*311*312*313ry
	baseimage2dockerfile_parse.parser.DockerfileParser.baseimage
builtins.str"builtins.str*38*39*310*311*312*313rm
cmd,dockerfile_parse.parser.DockerfileParser.cmd
builtins.str"builtins.str*38*39*310*311*312*313rŒ
labels/dockerfile_parse.parser.DockerfileParser.labelsw
)typing.Mapping[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"typing.Mapping*38*39*310*311*312*313r 
envs-dockerfile_parse.parser.DockerfileParser.envsw
)typing.Mapping[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"typing.Mapping*38*39*310*311*312*313r 
args-dockerfile_parse.parser.DockerfileParser.argsw
)typing.Mapping[builtins.str,builtins.str]
builtins.str"builtins.str
builtins.str"builtins.str"typing.Mapping*38*39*310*311*312*313≈

image_from"dockerfile_parse.parser.image_from"»
8Tuple[Union[builtins.str,None],Union[builtins.str,None]]D
Union[builtins.str,None]
builtins.str"builtins.str
NoneD
Union[builtins.str,None]
builtins.str"builtins.str
None*,

from_value
builtins.str"builtins.strz38z39z310z311z312z313*Ø
__annotations__'dockerfile_parse.parser.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict*38*39*310*311*312*313*f
loggerdockerfile_parse.parser.logger 
logging.Logger"logging.Logger*38*39*310*311*312*313