
dockerfile_parseÄ
DockerfileParser(dockerfile_parse.parser.DockerfileParser"builtins.object*‹
__init__*

self(*
path (*
cache_content (*
env_replace (*

parent_env (*
fileobj (	*

build_args (*0
	structure*

self(0:builtins.property`*+
json*

self(0:builtins.property`*4
is_multistage*

self(0:builtins.property`*b
	add_lines*

self(*
lines(*

all_stages (*
at_start (*
skip_scratch (*W
add_lines_at*

self(*
anchor(*
lines(*
replace (*
after (*8
context_structure*

self(0:builtins.property`r
fileobj0r
dockerfile_path0r
cache_content0r
cached_content0r
env_replace0r

parent_env0r

build_args0r	
lines0r
content0r
parent_images0r
	baseimage0r
cmd0r

labels0r
envs0r
args0*
__path__0*
__annotations__0*
__version__022*"(dockerfile_parse.parser.DockerfileParser2"builtins.str222"builtins.bool2"builtins.dict2222"	typing.IO22222/"(dockerfile_parse.parser._InstructionDict2
2"builtins.list2222"builtins.int2"builtins.dict2222"dockerfile_parse.util.Context2"builtins.list22"builtins.list22"typing.Sequence22"typing.Mapping222"builtins.dict2