
dockerfile_parse.constants*«
__annotations__*dockerfile_parse.constants.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict*36*37*38*39*310*x
DOCKERFILE_FILENAME.dockerfile_parse.constants.DOCKERFILE_FILENAME
builtins.str"builtins.str*36*37*38*39*310*x
COMMENT_INSTRUCTION.dockerfile_parse.constants.COMMENT_INSTRUCTION
builtins.str"builtins.str*36*37*38*39*310