from typing import Tuple

class Channel(CustomStubBase):
    def exec_command(self, *args, **kwargs) -> Tuple: ...
    def send(self, *args, **kwargs) -> int: ...
    def sendall(self, *args, **kwargs) -> None: ...
