class CursorWrapper(CustomStubBase):
    def execute(self, *args, **kwargs) -> None: ...
    def executemany(self, *args, **kwargs) -> None: ...
    def executescript(self, *args, **kwargs) -> None: ...
