/*
 * SonarQube Python Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.python.checks.utils;

import com.sonar.sslr.api.AstNode;
import org.junit.jupiter.api.Test;
import org.sonar.plugins.python.api.PythonFile;
import org.sonar.plugins.python.api.tree.FileInput;
import org.sonar.python.TestPythonVisitorRunner;
import org.sonar.python.parser.PythonParser;
import org.sonar.python.tree.PythonTreeMaker;

import static org.assertj.core.api.Assertions.assertThat;

class GeneratedFileUtilsTest {

  @Test
  void isGeneratedFileForReadabilityRules_detects_protobuf_generated_files() {
    String code = "# Generated by the protocol buffer compiler.\nx = 1";
    FileInput fileInput = parse(code);

    assertThat(GeneratedFileUtils.isGeneratedFileForReadabilityRules(pythonFile("service/user_pb2.py", code), fileInput)).isTrue();
    assertThat(GeneratedFileUtils.isGeneratedFileForReadabilityRules(pythonFile("service/user_pb2_grpc.py", code), fileInput)).isTrue();
    assertThat(GeneratedFileUtils.isGeneratedFileForReadabilityRules(pythonFile("service/user_pb2_test.py", code), fileInput)).isFalse();
  }

  @Test
  void isGeneratedFileForReadabilityRules_detects_grpc_generated_files() {
    String code = "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\nx = 1";
    FileInput fileInput = parse(code);

    assertThat(GeneratedFileUtils.isGeneratedFileForReadabilityRules(pythonFile("service/user_pb2_grpc.py", code), fileInput)).isTrue();
  }

  @Test
  void isGeneratedFileForReadabilityRules_requires_protobuf_generated_header() {
    FileInput fileInput = parse("x = 1");

    assertThat(GeneratedFileUtils.isGeneratedFileForReadabilityRules(pythonFile("service/user_pb2.py", "x = 1"), fileInput)).isFalse();
  }

  private static PythonFile pythonFile(String path, String content) {
    return new TestPythonVisitorRunner.MockPythonFile("", path, content);
  }

  private static FileInput parse(String code) {
    AstNode astNode = PythonParser.create().parse(code);
    return new PythonTreeMaker().fileInput(astNode);
  }
}
