class Message: ...

class Mail:
    def connect(self) -> None: ...
    def send(self, msg: Message) -> None: ...
    def send_message(self, subject: str, recipients: Optional[Any], body: Optional[Any], html: Optional[Any], sender: Optional[Any], cc: Optional[Any], bcc: Optional[Any], attachments: Optional[Any], reply_to: Optional[Any], date: Optional[Any], charset: Optional[Any], extra_headers: Optional[Any], mail_options: Optional[Any], rcpt_options: Optional[Any]) -> None: ...

class Connection:
    def send(self, msg: Message, envelope_from: Optional[Any]) -> None: ...
    def send_message(self, subject: str, recipients: Optional[Any], body: Optional[Any], html: Optional[Any], sender: Optional[Any], cc: Optional[Any], bcc: Optional[Any], attachments: Optional[Any], reply_to: Optional[Any], date: Optional[Any], charset: Optional[Any], extra_headers: Optional[Any], mail_options: Optional[Any], rcpt_options: Optional[Any]) -> None: ...
