name: 'Build Sonar Python'
description: 'Build both public and private modules of sonar-python'

runs:
  using: 'composite'
  steps:
    - name: Configure sonar-python project
      uses: ./.github/actions/config-sonar-python

    - name: Build public and private modules
      uses: SonarSource/ci-github-actions/build-maven@v1
      id: build
      with:
        maven-args: '-DskipTests=true -Dsonar.skip=true -P-typeshed_serializer'
        deploy-pull-request: true
        sonar-platform: none
        mixed-privacy: true
