from typing import Callable

class A1[T0: int = int, *T1, **T2](): ...
class A2[T0 = int, **T1, *T2](): ...
class A3[*T1=int, **T2=int](): ...
class A3[*T1=*Something, **T2=int](): ...

class B:
  def method[**T2, *T1](self, x: tuple[*T1], y: Callable[T2, None]) -> None:
    pass

