from SonarPythonAnalyzerFakeStub import CustomStubBase
from typing import Any


class Models(CustomStubBase):
    def generate_content(self, *args, **kwargs) -> Any: ...
    def generate_content_stream(self, *args, **kwargs) -> Any: ...

class AsyncModels(CustomStubBase):
    def generate_content(self, *args, **kwargs) -> Any: ...
    def generate_content_stream(self, *args, **kwargs) -> Any: ...
