def func(results):
    print("a")
    print("b")
    print("c")
    print("d")
    print("e")
    if len(results) > 10:
        print("f")
        print("g")
        print("h")
        print("i")
        print("j")
        for result in results:
            print(result)
            print("k")
            print("l")
        print("m")
        print("n")
        print("o")
        print("p")
    print("q")
    print("r")
    print("s")
    print("t")
    print("u")
    print("v")
    print("w")
    print("x")
