s = "Hello world."
s = "Hello \world."
t = "Nice to \\ meet you"
t = "Nice to \ meet you"
u = r"Let's have \ lunch"
u = "Let's have \ lunch"
v = 'Hello world.'
v = 'Hello \world.'
w = """Hello \n world."""
w = """Hello \w world."""
