class A:
    ...

def foo(a, b):
    if type(a) == str:  # Noncompliant {{Use the `isinstance()` function here.}}
#              ^^
        ...
    if type(a) == A: # Noncompliant
        ...
    if isinstance(a, str):
        ...
    if str == type(a):  # Noncompliant
        ...
    if bar(a) == str:
        ...
    if unknown(a) == str:
        ...
    t = type(a)
    if t == str: # FN
        ...
    if type(a) == type(b): # OK
        ...

    if type(a) == get_class(): # FN
        ...

def get_class():
    return str


def bar(a):
    ...
