def except_star_caught_exception_group():
    try:
        ...
    except* ExceptionGroup: # Noncompliant {{Exception group cannot be caught by an except*.}}
#   ^^^^^^
        ...
    except* BaseExceptionGroup: # Noncompliant
        ...

def except_star_caught_exception_group_multiple():
    try:
        ...
    except* (TypeError, ExceptionGroup): # Noncompliant
        ...
    except* (ExceptionGroup, BaseExceptionGroup): # Noncompliant
        ...
    except* (TypeError, ValueError):
        ...

def except_star_caught_valid_exception():
    try:
        ...
    except* ValueError:
        ...

def except_caught_exception_group():
    try:
        ...
    except ValueError:
        ...
    except ExceptionGroup:
        ...
    except BaseExceptionGroup:
        ...
    except (TypeError, ExceptionGroup):
        ...
    except (ExceptionGroup, BaseExceptionGroup):
        ...
    except (TypeError, ValueError):
        ...

def except_caught_global():
    try:
        ...
    except:
        ...

