def except_star_caught_exception_group():
    try:
        ...
    except* ExceptionGroup: # Noncompliant {{Avoid catching ExceptionGroup exception with 'except*'}}
#   ^^^^^^^
        ...
    except* BaseExceptionGroup: # Noncompliant {{Avoid catching BaseExceptionGroup exception with 'except*'}}
        ...

def except_star_caught_exception_group_multiple():
    try:
        ...
    except* (TypeError, ExceptionGroup): # Noncompliant
        ...
    except* (ExceptionGroup, BaseExceptionGroup): # Noncompliant 2
        ...
    except* (TypeError, ValueError):
        ...

def except_star_caught_valid_exception():
    try:
        ...
    except* ValueError:
        ...

def except_caught_exception_group():
    try:
        ...
    except ValueError:
        ...
    except ExceptionGroup:
        ...
    except BaseExceptionGroup:
        ...
    except (TypeError, ExceptionGroup):
        ...
    except (ExceptionGroup, BaseExceptionGroup):
        ...
    except (TypeError, ValueError):
        ...

def except_caught_global():
    try:
        ...
    except:
        ...

def exception_group_replaced():
    ExceptionGroup = 5
    try:
        ...
    # FP : should not be raised as it is no more the original ExceptionGroup class
    except* ExceptionGroup: # Noncompliant
        ...
