class A(Exception): ...
class B(BaseException): ... # Noncompliant {{Derive this class from "Exception" instead of "BaseException".}}
class C(GeneratorExit): ... # Noncompliant {{Derive this class from "Exception" instead of "GeneratorExit".}}
class D(KeyboardInterrupt): ... # Noncompliant
class E(SystemExit): ... # Noncompliant
class F(42): ...
class G(): ...
class H(*[BaseException]): ...
class I(Unknown): ...

