from typing import Generic
class SomeGeneric(Generic[T]):
  ...

class SomeGenericWithTypeParam[T](): ...

class MyImportedGenericTypeVarChild(SomeGeneric[T]): ...
class MyImportedNonGenericChild(SomeGeneric): ...
class MyImportedConcreteChild(SomeGeneric[str]): ...
