from typing import Generic, TypeVar

T = TypeVar('T')

class SomeGeneric(Generic[T]):
  ...

class SomeGenericWithTypeParam[T](): ...

class MyImportedGenericTypeVarChild(SomeGeneric[T]): ...
class MyImportedNonGenericChild(SomeGeneric): ...
class MyImportedConcreteChild(SomeGeneric[str]): ...

# U has not been defined
class SomeGenericIncorrectlyDefined(Generic[U]):
    ...
