from SonarPythonAnalyzerFakeStub import CustomStubBase
from typing import Any, Type, Union, List, Optional


class ShellTool(CustomStubBase):
    process: Any = ...
    name: str = ...
    description: str = ...
    args_schema: Type[BaseModel] = ...
    ask_human_input: bool = ...

    def _run(
            self,
            commands: Union[str, List[str]],
            run_manager: Optional[CallbackManagerForToolRun] = ...,
    ) -> str: ...
