from SonarPythonAnalyzerFakeStub import CustomStubBase

from typing import Any, Iterator

class Manager(CustomStubBase):

    # Queryset-returning methods (chainable)
    def all(self) -> Manager: ...
    def filter(self, *args, **kwargs) -> Manager: ...
    def exclude(self, *args, **kwargs) -> Manager: ...
    def order_by(self, *field_names) -> Manager: ...
    def reverse(self) -> Manager: ...
    def distinct(self, *field_names) -> Manager: ...
    def select_related(self, *fields) -> Manager: ...
    def prefetch_related(self, *lookups) -> Manager: ...
    def defer(self, *fields) -> Manager: ...
    def only(self, *fields) -> Manager: ...
    def using(self, alias) -> Manager: ...
    def annotate(self, *args, **kwargs) -> Manager: ...
    def alias(self, *args, **kwargs) -> Manager: ...
    def none(self) -> Manager: ...
    def union(self, *other_qs, all=False) -> Manager: ...
    def intersection(self, *other_qs) -> Manager: ...
    def difference(self, *other_qs) -> Manager: ...
    def select_for_update(self, nowait=False, skip_locked=False, of=(), no_key=False) -> Manager: ...
    def extra(self, *args, **kwargs) -> Manager: ...
    def values(self, *fields, **expressions) -> Manager: ...
    def values_list(self, *fields, flat=False, named=False) -> Manager: ...
    def dates(self, field_name, kind, order=...) -> Manager: ...
    def datetimes(self, field_name, kind, order=..., tzinfo=None) -> Manager: ...

    # Methods returning single objects
    def get(self, *args, **kwargs) -> Any: ...
    def create(self, **kwargs) -> Any: ...
    def get_or_create(self, defaults=None, **kwargs) -> tuple: ...
    def update_or_create(self, defaults=None, create_defaults=None, **kwargs) -> tuple: ...
    def first(self) -> Any: ...
    def last(self) -> Any: ...
    def earliest(self, *fields) -> Any: ...
    def latest(self, *fields) -> Any: ...

    # Methods returning scalar/collection values
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def contains(self, obj) -> bool: ...
    def aggregate(self, *args, **kwargs) -> dict: ...
    def in_bulk(self, id_list=None, *, field_name=...) -> dict: ...
    def update(self, **kwargs) -> int: ...
    def delete(self) -> tuple: ...
    def bulk_create(self, objs, batch_size=None, **kwargs) -> list: ...
    def bulk_update(self, objs, fields, batch_size=None) -> int: ...
    def iterator(self, chunk_size=None) -> Iterator: ...
    def explain(self, *, format=None, **options) -> str: ...
    def raw(self, *args, **kwargs) -> Any: ...
