name: 'Analyze Sonar Python'
description: 'Run SonarQube analysis for sonar-python project'
inputs:
  sonarqube-instance:
    description: 'SonarQube instance, can be next, sqc-eu, sqc-us'
    required: true
  sonar-project-key:
    description: 'SonarQube project key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Analysis
      uses: SonarSource/ci-github-actions/build-maven@v1
      with:
        maven-args: >-
          -Dsonar.organization=sonarsource -Dsonar.projectKey=${{ inputs.sonar-project-key }}
          -Dsonar.analysisCache.enabled=true -Dsonar.sca.recursiveManifestSearch=true -DgenerateTypeshedStubs -DfailStubGenerationFast=true -Dskip.its=true
        deploy: false
        sonar-platform: ${{ inputs.sonarqube-instance }}
        scanner-java-opts: '-Xmx1G'
