name: 'Analyze Sonar Python'
description: 'Run SonarQube analysis for sonar-python project'
inputs:
  sonar-host-url:
    description: 'SonarQube host URL'
    required: true
  sonar-project-key:
    description: 'SonarQube project key'
    required: true
  build-number:
    description: 'Build number for analysis'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get sonar token
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/next token | SONAR_TOKEN;

    # This step uses a custom script instead of the SonarSource/ci-github-actions/build-maven action because this step should not deploy anything to Artifactory. 
    # Unfortunately, this currently cannot be disabled in the build-maven action. See BUILD-9394 for details
    - name: Run Analysis
      shell: bash
      run: bash ${{ github.action_path }}/analyze.sh
      env:
        SONAR_TOKEN: ${{ fromJson(steps.secrets.outputs.vault).SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
        BUILD_NUMBER: ${{ inputs.build-number }}
        GIT_SHA1: ${{ github.sha }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
        GITHUB_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        PULL_REQUEST: ${{ github.event.pull_request.number || 'false' }}
        PIPELINE_ID: ${{ inputs.build-number }}
