/*
 * SonarQube Python Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.python.checks.quickfix;

import java.lang.reflect.Method;
import org.junit.jupiter.api.Test;
import org.opentest4j.AssertionFailedError;
import org.sonar.plugins.python.api.PythonCheck;
import org.sonar.plugins.python.api.PythonSubscriptionCheck;
import org.sonar.plugins.python.api.quickfix.PythonQuickFix;
import org.sonar.plugins.python.api.quickfix.PythonTextEdit;
import org.sonar.plugins.python.api.tree.AssignmentStatement;
import org.sonar.plugins.python.api.tree.Tree;
import org.sonar.python.quickfix.TextEditUtils;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PythonQuickFixVerifierTest {

  @Test
  void no_issue_found() {
    PythonCheck check = new SimpleCheck();
    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(check, "a,b,c", ""))
      .isInstanceOf(AssertionError.class)
      .hasMessage("[Number of issues] Expected 1 issue but found 0");
  }

  @Test
  void more_than_one_issue_raised() {
    PythonCheck check = new SimpleCheck();
    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(check, "a=10;b=3", ""))
      .isInstanceOf(AssertionError.class)
      .hasMessage("[Number of issues] Expected 1 issue but found 2");
  }

  @Test
  void one_issue_raised_no_quickfix() {
    PythonCheck check = new SimpleCheckNoQuickFix();

    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(check, "a=10", ""))
      .isInstanceOf(AssertionError.class)
      .hasMessage("[Number of quickfixes] Expected 1 quickfix but found 0");
  }

  @Test
  void one_issue_one_qf_wrong_fix() {
    var expectedMsg = ("""
      [The code with the quickfix applied is not the expected result.
      Applied QuickFixes are:
      [a!=10]
      Expected result:
      [a==10]]
      expected: ["a==10"]
      but was: ["a!=10"]
      """).replaceAll("\\s+", "");

    SimpleCheck simpleCheck = new SimpleCheck();
    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(simpleCheck, "a=10", "a==10"))
      .isInstanceOf(AssertionFailedError.class)
      .extracting(Throwable::getMessage)
      .extracting(s -> s.replaceAll("\\s+", ""))
      .isEqualTo(expectedMsg);
  }

  @Test
  void test_verify() {
    PythonQuickFixVerifier.verify(new SimpleCheck(), "a=10", "a!=10");
  }

  @Test
  void test_verify_no_quickfixes_wrapper() {
    PythonQuickFixVerifier.verifyNoQuickFixes(new SimpleCheckNoQuickFix(), "a=10");
  }

  @Test
  void test_verify_quick_fix_messages_wrapper() {
    PythonQuickFixVerifier.verifyQuickFixMessages(new SimpleCheck(), "a=10", "Add '!' here.");
  }

  @Test
  void test_verify_invalid_after() {
    var expectedMsg = """
      [Correction of quick fixes] The code expected to be generated by the quickfix is not valid (I)Python code.
      Results is :
      [a!!=10]""";
    var check = new SimpleCheck();
    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(check, "a=10", "a!!=10"))
      .isInstanceOf(AssertionError.class)
      .extracting(Throwable::getMessage)
      .isEqualTo(expectedMsg);
  }

  @Test
  void verifyIPython() {
    PythonQuickFixVerifier.verifyIPython(new SimpleCheck(), "a=10\n?a", "a!=10\n?a");
    PythonQuickFixVerifier.verifyIPythonQuickFixMessages(new SimpleCheck(), "a=10\n?a", "Add '!' here.");
  }

  @Test
  void verifyIPythonNoQuickFixes() {
    PythonQuickFixVerifier.verifyIPythonNoQuickFixes(new SimpleCheckNoQuickFix(), "a=10\n?a");
  }

  @Test
  void test_multiple_lines() {
    PythonQuickFixVerifier.verify(new SimpleCheck(), "b \na=10", "b \na!=10");
  }

  @Test
  void verify_semantic() {
    PythonQuickFixVerifier.verifySemantic(new SimpleCheck(), "pkg/test_file.py", "a=10", "a!=10");
    PythonQuickFixVerifier.verifySemanticQuickFixMessages(new SimpleCheck(), "pkg/test_file.py", "a=10", "Add '!' here.");
  }

  @Test
  void verify_semantic_no_quickfix() {
    PythonQuickFixVerifier.verifySemanticNoQuickFixes(new SimpleCheckNoQuickFix(), "pkg/test_file.py", "a=10");
  }

  @Test
  void test_multiple_text_edits_are_sorted_and_apply_on_windows_line_endings() {
    PythonQuickFixVerifier.verify(new MultipleEditsCheck(), "a=10\r\nb=3", "a!=10\r\nb!=3");
  }

  @Test
  void test_colliding_multiple_text_edits_fail() {
    var check = new CollidingEditsCheck();
    assertThatThrownBy(() -> PythonQuickFixVerifier.verify(check, "a=10", ""))
      .isInstanceOf(IllegalArgumentException.class)
      .hasMessage("There is a collision between the range of the quickfixes.");
  }

  @Test
  void collision_helpers_cover_remaining_branches() throws Exception {
    Method oneEnclosedByTheOther = PythonQuickFixVerifier.class.getDeclaredMethod("oneEnclosedByTheOther", PythonTextEdit.class, PythonTextEdit.class);
    Method sameLineIntersection = PythonQuickFixVerifier.class.getDeclaredMethod("sameLineIntersection", PythonTextEdit.class, PythonTextEdit.class);
    Method explodedEditsIntersect = PythonQuickFixVerifier.class.getDeclaredMethod("explodedEditsIntersect", PythonTextEdit.class, PythonTextEdit.class);
    Method onSameLine = PythonQuickFixVerifier.class.getDeclaredMethod("onSameLine", PythonTextEdit.class, PythonTextEdit.class);
    Method compactOnDifferentLines = PythonQuickFixVerifier.class.getDeclaredMethod("compactOnDifferentLines", PythonTextEdit.class, PythonTextEdit.class);
    Method isCompact = PythonQuickFixVerifier.class.getDeclaredMethod("isCompact", PythonTextEdit.class);
    Method isSecondInFirst = PythonQuickFixVerifier.class.getDeclaredMethod("isSecondInFirst", PythonTextEdit.class, PythonTextEdit.class);
    Method noLineIntersection = PythonQuickFixVerifier.class.getDeclaredMethod("noLineIntersection", PythonTextEdit.class, PythonTextEdit.class);
    oneEnclosedByTheOther.setAccessible(true);
    sameLineIntersection.setAccessible(true);
    explodedEditsIntersect.setAccessible(true);
    onSameLine.setAccessible(true);
    compactOnDifferentLines.setAccessible(true);
    isCompact.setAccessible(true);
    isSecondInFirst.setAccessible(true);
    noLineIntersection.setAccessible(true);

    PythonTextEdit sameLineLeft = new PythonTextEdit("", 1, 0, 1, 0);
    PythonTextEdit sameLineRight = new PythonTextEdit("", 1, 1, 1, 1);
    PythonTextEdit sameLineOverlap = new PythonTextEdit("", 1, 0, 1, 2);
    assertBoolean(sameLineIntersection, false, sameLineLeft, sameLineRight);
    assertBoolean(sameLineIntersection, true, sameLineOverlap, sameLineRight);
    assertBoolean(onSameLine, true, sameLineOverlap, sameLineRight);

    PythonTextEdit compact = new PythonTextEdit("", 2, 0, 2, 1);
    PythonTextEdit compactSameStart = new PythonTextEdit("", 1, 1, 1, 3);
    PythonTextEdit compactSameEnd = new PythonTextEdit("", 3, 0, 3, 2);
    PythonTextEdit compactOtherLine = new PythonTextEdit("", 5, 0, 5, 1);
    PythonTextEdit exploded = new PythonTextEdit("", 1, 0, 3, 0);
    PythonTextEdit explodedSameEnd = new PythonTextEdit("", 1, 0, 3, 3);
    PythonTextEdit separate = new PythonTextEdit("", 4, 0, 5, 0);
    PythonTextEdit touchingEnd = new PythonTextEdit("", 2, 1, 4, 0);
    PythonTextEdit crossingEnd = new PythonTextEdit("", 2, 0, 4, 0);
    PythonTextEdit touchingStart = new PythonTextEdit("", 1, 0, 2, 1);
    PythonTextEdit explodedEnclosing = new PythonTextEdit("", 1, 0, 4, 0);
    PythonTextEdit explodedEnclosed = new PythonTextEdit("", 2, 0, 3, 0);

    assertBoolean(compactOnDifferentLines, true, compact, compactOtherLine);
    assertBoolean(isCompact, true, compact);
    assertBoolean(isCompact, false, exploded);
    assertBoolean(isSecondInFirst, true, compactSameStart, exploded);
    assertBoolean(isSecondInFirst, true, compactSameEnd, explodedSameEnd);
    assertBoolean(isSecondInFirst, false, compact, separate);
    assertBoolean(noLineIntersection, true, exploded, separate);
    assertBoolean(noLineIntersection, false, exploded, touchingEnd);
    assertBoolean(oneEnclosedByTheOther, true, sameLineOverlap, sameLineRight);
    assertBoolean(oneEnclosedByTheOther, false, compact, compactOtherLine);
    assertBoolean(oneEnclosedByTheOther, true, compactSameStart, exploded);
    assertBoolean(oneEnclosedByTheOther, true, explodedSameEnd, compactSameEnd);
    assertBoolean(oneEnclosedByTheOther, true, explodedEnclosing, explodedEnclosed);
    assertBoolean(explodedEditsIntersect, false, exploded, separate);
    assertBoolean(explodedEditsIntersect, true, touchingStart, crossingEnd);
    assertBoolean(explodedEditsIntersect, true, explodedEnclosing, explodedEnclosed);
  }

  private static void assertBoolean(Method method, boolean expected, Object... args) throws Exception {
    org.assertj.core.api.Assertions.assertThat(method.invoke(null, args)).isEqualTo(expected);
  }

  private class SimpleCheck extends PythonSubscriptionCheck {

    @Override
    public void initialize(Context context) {
      context.registerSyntaxNodeConsumer(Tree.Kind.ASSIGNMENT_STMT, ctx -> {
        AssignmentStatement assignment = ((AssignmentStatement) ctx.syntaxNode());
        PreciseIssue issue = ctx.addIssue(assignment.equalTokens().get(0), "");

        PythonTextEdit text = TextEditUtils
          .insertBefore(assignment.equalTokens().get(0), "!");
        PythonQuickFix quickFix = PythonQuickFix.newQuickFix("Add '!' here.")
          .addTextEdit(text)
          .build();
        issue.addQuickFix(quickFix);
      });
    }
  }

  private class SimpleCheckNoQuickFix extends PythonSubscriptionCheck {
    @Override
    public void initialize(Context context) {
      context.registerSyntaxNodeConsumer(Tree.Kind.ASSIGNMENT_STMT, ctx -> ctx.addIssue(ctx.syntaxNode(), ""));
    }
  }

  private class MultipleEditsCheck extends PythonSubscriptionCheck {
    @Override
    public void initialize(Context context) {
      context.registerSyntaxNodeConsumer(Tree.Kind.ASSIGNMENT_STMT, ctx -> {
        AssignmentStatement assignment = (AssignmentStatement) ctx.syntaxNode();
        if (assignment.firstToken().line() != 1) {
          return;
        }
        PreciseIssue issue = ctx.addIssue(assignment.equalTokens().get(0), "");
        PythonQuickFix quickFix = PythonQuickFix.newQuickFix("Add '!' here.")
          .addTextEdit(new PythonTextEdit("!", 2, 1, 2, 1))
          .addTextEdit(TextEditUtils.insertBefore(assignment.equalTokens().get(0), "!"))
          .build();
        issue.addQuickFix(quickFix);
      });
    }
  }

  private class CollidingEditsCheck extends PythonSubscriptionCheck {
    @Override
    public void initialize(Context context) {
      context.registerSyntaxNodeConsumer(Tree.Kind.ASSIGNMENT_STMT, ctx -> {
        AssignmentStatement assignment = (AssignmentStatement) ctx.syntaxNode();
        PreciseIssue issue = ctx.addIssue(assignment.equalTokens().get(0), "");
        PythonQuickFix quickFix = PythonQuickFix.newQuickFix("Broken quickfix")
          .addTextEdit(new PythonTextEdit("!", 1, 1, 1, 1))
          .addTextEdit(new PythonTextEdit("!=", 1, 1, 1, 2))
          .build();
        issue.addQuickFix(quickFix);
      });
    }
  }
}
