from typing import Any

class RSAPublicKey:
    def encrypt(self, plaintext: Any, padding: Any) -> Any: ...

class RSAPrivateKey:
    def decrypt(self, ciphertext: Any, padding: Any) -> Any: ...
    def public_key(self) -> RSAPublicKey: ...

def generate_private_key(public_exponent: Any, key_size: Any, backend: Any) -> RSAPrivateKey: ...
