class C:
    def hasSelf01(self):
        ...

    def hasSelf02(sth): # Any kind of name is accepted for the first parameter by the implementation
        ...

    def hasSelf03(self, sth):
        ...

    def hasNoSelf01():
        ...

    def hasNoSelf02((x, y)): # Python 2
        ...

    def hasNoSelf02(*, x):
        ...

def hasSelf04(sth): # The implementation does not check whether the function definition is a method
    ...
