from SonarPythonAnalyzerFakeStub import CustomStubBase
from typing import List, Optional, Type


class CodeInterpreterTool(CustomStubBase):
    def __init__(
            self,
            name: str = ...,
            description: str = ...,
            args_schema: Type[BaseModel] = ...,
            default_image_tag: str = ...,
            code: Optional[str] = ...,
            user_dockerfile_path: Optional[str] = ...,
            user_docker_base_url: Optional[str] = ...,
            unsafe_mode: bool = ...) -> CodeInterpreterTool: ...

    def _get_installed_package_path() -> str: ...

    def _verify_docker_image(self) -> None: ...

    def _run(self, **kwargs) -> str: ...

    def _install_libraries(self, container: Container, libraries: List[str]) -> None: ...

    def _init_docker_container(self) -> Container: ...

    def _check_docker_available(self) -> bool: ...

    def run_code_safety(self, code: str, libraries_used: List[str]) -> str: ...

    def run_code_in_docker(self, code: str, libraries_used: List[str]) -> str: ...

    def run_code_in_restricted_sandbox(self, code: str) -> str: ...

    def run_code_unsafe(self, code: str, libraries_used: List[str]) -> str: ...
