/*
 * SonarQube Python Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.python.checks.utils;

import org.sonar.plugins.python.api.PythonFile;
import org.sonar.plugins.python.api.tree.Tree;
import org.sonar.python.checks.django.DjangoUtils;

public final class GeneratedFileUtils {
  private static final String PROTOBUF_GENERATED_MARKER = "# Generated by the protocol buffer compiler.";
  private static final String GRPC_GENERATED_MARKER = "# Generated by the gRPC Python protocol compiler plugin.";

  private GeneratedFileUtils() {
  }

  public static boolean isGeneratedFileForReadabilityRules(PythonFile pythonFile, Tree tree) {
    return DjangoUtils.isDjangoGeneratedMigrationFile(pythonFile, tree) || isProtobufGeneratedFile(pythonFile);
  }

  private static boolean isProtobufGeneratedFile(PythonFile pythonFile) {
    String path = pythonFile.uri().getPath();
    if (path == null) {
      return false;
    }

    String normalizedPath = path.replace('\\', '/');
    if (!normalizedPath.endsWith("_pb2.py") && !normalizedPath.endsWith("_pb2_grpc.py")) {
      return false;
    }

    return pythonFile.content().contains(PROTOBUF_GENERATED_MARKER)
      || pythonFile.content().contains(GRPC_GENERATED_MARKER);
  }
}
