from typing import Any, Callable, List

def require_http_methods(request_method_list: List[str]) -> Callable[..., Any]: ...
def require_GET(*args: Any, **kwargs: Any) -> Any: ...
def require_POST(*args: Any, **kwargs: Any) -> Any: ...
def require_safe(*args: Any, **kwargs: Any) -> Any: ...
