all:
	-nosetests tests_locatable/test_locatable.py --with-xunit --xunit-file=nosetests_locatable.xml
	-nosetests tests_unlocatable/subdir/test_unlocatable.py --with-xunit --xunit-file=nosetests_unlocatable.xml
