from django.urls import path

from . import views
from . import views_decorator_fqn_null

urlpatterns = [
  path('compliant_explicit_methods', views.compliant_explicit_methods, name='compliant_explicit_methods'),
  path('compliant_require_http_methods', views.compliant_require_http_methods, name='compliant_require_http_methods'),
  path('compliant_require_http_methods2', views.compliant_require_http_methods2, name='compliant_require_http_methods2'),
  path('compliant_require_http_methods3', views.compliant_require_http_methods3, name='compliant_require_http_methods3'),
  path('compliant_require_http_methods4', views.compliant_require_http_methods4, name='compliant_require_http_methods4'),
  path('compliant_non_django_import', views.compliant_non_django_import, name='compliant_non_django_import'),
  path('compliant_require_http_methods5', views.compliant_require_http_methods5, name='compliant_require_http_methods5'),
  path('compliant_require_http_methods6', views.compliant_require_http_methods6, name='compliant_require_http_methods6'),
  path('compliant', views_decorator_fqn_null.compliant, name='compliant'),
  path('compliant_require_post', views.compliant_require_post, name='compliant_require_post'),
  path('compliant_require_get', views.compliant_require_get, name='compliant_require_get'),
  path('compliant_require_safe', views.compliant_require_safe, name='compliant_require_safe'),
  path('compliant_method_eq_check', views.compliant_method_eq_check, name='compliant_method_eq_check'),
  path('compliant_method_eq_check_swapped', views.compliant_method_eq_check_swapped, name='compliant_method_eq_check_swapped'),
  path('compliant_method_in_check', views.compliant_method_in_check, name='compliant_method_in_check'),
  path('compliant_method_check_and_condition', views.compliant_method_check_and_condition, name='compliant_method_check_and_condition'),
  path('compliant_method_check_parenthesized', views.compliant_method_check_parenthesized, name='compliant_method_check_parenthesized'),
  path('compliant_method_check_elif', views.compliant_method_check_elif, name='compliant_method_check_elif'),
  path('compliant_method_check_in_nested_scope', views.compliant_method_check_in_nested_scope, name='compliant_method_check_in_nested_scope'),
  path('noncompliant_nested_function', views.noncompliant_nested_function, name='noncompliant_nested_function'),
  path('noncompliant_lambda', views.noncompliant_lambda, name='noncompliant_lambda'),
  path('noncompliant1', views.noncompliant1, name='noncompliant1'),
  path('noncompliant_other_dec', views.noncompliant_other_dec, name='noncompliant_other_dec'),
  path('noncompliant_login_required', views.noncompliant_login_required, name='noncompliant_login_required'),
  path('noncompliant_permission_required', views.noncompliant_permission_required, name='noncompliant_permission_required'),
  path('noncompliant_method_on_other_var', views.noncompliant_method_on_other_var, name='noncompliant_method_on_other_var'),
  path('noncompliant_method_on_different_var', views.noncompliant_method_on_different_var, name='noncompliant_method_on_different_var'),
  path('noncompliant_other_if_eq_check', views.noncompliant_other_if_eq_check, name='noncompliant_other_if_eq_check'),
  path('noncompliant_method_truthy_check', views.noncompliant_method_truthy_check, name='noncompliant_method_truthy_check'),
  path('noncompliant_method_and_check', views.noncompliant_method_and_check, name='noncompliant_method_and_check'),
  path('noncompliant_method_only_printed', views.noncompliant_method_only_printed, name='noncompliant_method_only_printed'),
  path('noncompliant_method_comparison_not_in_if', views.noncompliant_method_comparison_not_in_if, name='noncompliant_method_comparison_not_in_if'),
  path('noncompliant_request_used_as_argument', views.noncompliant_request_used_as_argument, name='noncompliant_request_used_as_argument'),
  path('noncompliant_tuple_param_only', views.noncompliant_tuple_param_only, name='noncompliant_tuple_param_only'),
]
