class Connection(CustomStubBase):
    def execute(self, *args, **kwargs): ...

class Engine(CustomStubBase):
    def connect(self, *args, **kwargs) -> Connection: ...
    def execute(self, *args, **kwargs): ...
