from SonarPythonAnalyzerFakeStub import CustomStubBase
from _pytest.fixtures import FixtureRequest

class ApproxScalar(CustomStubBase): ...

def approx(expected: object = ..., *args: object, **kwargs: object) -> ApproxScalar: ...
def fixture(*args: object, **kwargs: object): ...
def yield_fixture(*args: object, **kwargs: object): ...
def fail(*args: object, **kwargs: object): ...
def raises(*args: object, **kwargs: object): ...
def warns(*args: object, **kwargs: object): ...

import pytest.mark as mark
