class View:
    def dispatch(self, request, *args, **kwargs): ...
    def get_context_data(self, **kwargs): ...

class TemplateView(View):
    template_name: str
    def get_context_data(self, **kwargs): ...
