from typing import Any, Dict, List, Optional, Type

from django.forms import Form
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View
from django.views.generic.detail import (
    BaseDetailView,
    SingleObjectMixin,
    SingleObjectTemplateResponseMixin,
)

class FormMixin(ContextMixin):
    initial: Dict[str, Any]
    form_class: Optional[Type[Form]]
    success_url: Optional[str]
    prefix: Optional[str]
    def get_initial(self) -> Dict[str, Any]: ...
    def get_prefix(self) -> Optional[str]: ...
    def get_form_class(self) -> Type[Form]: ...
    def get_form(self, form_class: Optional[Type[Form]] = ...) -> Form: ...
    def get_form_kwargs(self) -> Dict[str, Any]: ...
    def get_success_url(self) -> str: ...
    def form_valid(self, form: Form) -> HttpResponse: ...
    def form_invalid(self, form: Form) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]: ...

class ModelFormMixin(FormMixin, SingleObjectMixin):
    fields: Optional[Any]
    def get_form_class(self) -> Type[Form]: ...
    def get_form_kwargs(self) -> Dict[str, Any]: ...
    def get_success_url(self) -> str: ...
    def form_valid(self, form: Form) -> HttpResponse: ...

class ProcessFormView(View):
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def put(self, *args: Any, **kwargs: Any) -> HttpResponse: ...

class BaseFormView(FormMixin, ProcessFormView):
    pass

class FormView(TemplateResponseMixin, BaseFormView):
    pass

class BaseCreateView(ModelFormMixin, ProcessFormView):
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class CreateView(SingleObjectTemplateResponseMixin, BaseCreateView):
    template_name_suffix: str

class BaseUpdateView(ModelFormMixin, ProcessFormView):
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class UpdateView(SingleObjectTemplateResponseMixin, BaseUpdateView):
    template_name_suffix: str

class DeletionMixin:
    success_url: Optional[str]
    def delete(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...

class BaseDeleteView(DeletionMixin, FormMixin, BaseDetailView):
    form_class: Type[Form]
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def form_valid(self, form: Form) -> HttpResponse: ...

class DeleteView(SingleObjectTemplateResponseMixin, BaseDeleteView):
    template_name_suffix: str
