from typing import Any, Dict, Optional

class BaseCookie(Dict[Any, Any]):
    def value_decode(self, val): ...
    def value_encode(self, val): ...
    def __init__(self, input: Optional[Any] = ...): ...
    def __setitem__(self, key, value): ...
    def output(self, attrs: Optional[Any] = ..., header=..., sep=...): ...
    def js_output(self, attrs: Optional[Any] = ...): ...
    def load(self, rawdata): ...

class SimpleCookie(BaseCookie):
    def value_decode(self, val): ...
    def value_encode(self, val): ...

class SerialCookie(BaseCookie):
    def __init__(self, input: Optional[Any] = ...): ...
    def value_decode(self, val): ...
    def value_encode(self, val): ...

class SmartCookie(BaseCookie):
    def __init__(self, input: Optional[Any] = ...): ...
    def value_decode(self, val): ...
    def value_encode(self, val): ...